config/routes.rb
Rails.application.routes.draw do
  resources :pages, except: [:create] do
    post 'analyse', on: :collection
  end
  resources :projects
  devise_for :users
  resources :lighthouse_reports, except: [:edit, :update] do
    get 'detail/:strategy', action: :detail, as: :detail
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'application#home'
end

app/views/pages/_form.html.slim
= form_for @page||=Page.new do |f|
  - if @page.errors.any?
    #error_explanation
      h2 = "#{pluralize(@page.errors.count, "error")} prohibited this page from being saved:"
      ul
        - @page.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :url
    = f.text_field :url, placeholder: 'Enter a web page URL', required: true
  .actions = f.submit 'Analyze'

app/views/pages/index.html.slim
h1 Listing pages

table
  thead
    tr
      th Path
      th Project
      th
      th
      th

  tbody
    - @pages.each do |page|
      tr
        td = page.path
        td = page.project
        td = link_to 'Show', page
        td = link_to 'Edit', edit_page_path(page)
        td = link_to 'Destroy', page, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Page', new_page_path

app/views/pages/new.html.slim
h1 New page

== render 'form'

= link_to 'Back', pages_path

app/views/pages/show.html.slim
= c 'analyzer/bar', url: @page.url
.layout-container
  h1 Page speed history
  h2 =@page.valid_url
  = c 'reports_recap', reports: @page.reports
  = c 'page/form', page: @page