config/routes.rb
Rails.application.routes.draw do
  resources :pages, except: [:create] do
    post 'analyse', on: :collection
  end
  resources :projects
  devise_for :users
  resources :lighthouse_reports, except: [:edit, :update] do
    get 'detail/:strategy', action: :detail, as: :detail
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'application#home'
end

app/models/project.rb
class Project < ApplicationRecord
  include ProjectsConcern
  belongs_to :user
  has_many :pages
  has_many :lighthouse_reports, through: :pages
  alias_attribute :reports,:lighthouse_reports


  def mean_score_mobile
    mean pages.map(&:score_mobile)
  end

  def mean_score_desktop
    mean pages.map(&:score_desktop)
  end

  def display_name
    name || domain
  end


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include ProjectsConcern
  before_action :authenticate_user!
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = current_user.projects
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    set_current_project(@project)
    @pages = @project.pages
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.user = current_user

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = current_user.projects.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def project_params
    params.require(:project).permit(:name, :domain)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.slim
= form_for @project do |f|
  - if @project.errors.any?
    #error_explanation
      h2 = "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      ul
        - @project.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name, placeholder: 'My website'
  .field
    = f.label :domain
    = f.text_field :domain, placeholder: 'example.com'
  .actions = f.submit

app/views/projects/edit.html.slim
.layout-container
  h1 Editing project

  == render 'form'

  =< link_to 'Back', projects_path

app/views/projects/index.html.slim
.layout-container
  .projects-head
    h2 My projects
    .projects-head-action
      = c 'button', label: 'New Project', href: new_project_path

  = c 'projects/table', projects: @projects

app/views/projects/new.html.slim
.layout-container
  h1 New project

  p Please fill in the website you want to monitor

  == render 'form'

  = link_to 'Back', projects_path

app/views/projects/show.html.slim
= c 'analyzer/bar', hidden: true
.layout-container

  = c "projects/header"

  p Performance is checked daily. Configure the pages you want to get alerted by email in case of significant score drop.



  = c "projects/recap"